/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/* @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro', 
    {
      type: 'category',
      label: 'Ebanux',
      items: ['ebanux/ebanux','ebanux/payment_links'],
    },	
    {
      type: 'category',
      label: 'Stripe',
      items: ['stripe/stripe','stripe/stripe_payment_links'],
    },	
    {
      type: 'category',
      label: 'Payoneer',
      items: ['payoneer/payoneer','payoneer/payoneer_payment_links'],
    },		
  ],
};

module.exports = sidebars;
